// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedisCaching.Data;

#nullable disable

namespace RedisCaching.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedisCaching.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Name = "Apple iPhone 14",
                            Price = 999,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            Name = "Samsung Galaxy S22",
                            Price = 899,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            Name = "Sony WH-1000XM4 Headphones",
                            Price = 349,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 4,
                            Category = "Footwear",
                            Name = "Nike Air Zoom Pegasus",
                            Price = 120,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 5,
                            Category = "Footwear",
                            Name = "Adidas Ultraboost",
                            Price = 180,
                            Quantity = 80
                        },
                        new
                        {
                            Id = 6,
                            Category = "Groceries",
                            Name = "Organic Apples (1kg)",
                            Price = 4,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 7,
                            Category = "Groceries",
                            Name = "Organic Bananas (1 Dozen)",
                            Price = 3,
                            Quantity = 150
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
